apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: second-sync
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/TheRealCDH/SecondSync.git
  ref:
    branch: main
