apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: SecondSync Dashboard
    base: http://100.67.54.105:30000
    layout:
      Management:
        style: cols-3
      Media:
        style: cols-3
      Download:
        style: cols-2
  
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/TheRealCDH/SecondSync/main/logo.png
    - resources:
        cpu: true
        memory: true
    - datetime:
        format:
          dateStyle: long
          timeStyle: short

  services.yaml: |
    - Management:
        - Jellyseerr:
            icon: jellyseerr.png
            href: http://100.67.54.105:30001
            description: Request Management
            widget:
              type: jellyseerr
              url: http://localhost:5055
              key: {{HOMEPAGE_VAR_API_KEY}}
        - Prowlarr:
            icon: prowlarr.png
            href: http://100.67.54.105:30005
            description: Indexer Management
            widget:
              type: prowlarr
              url: http://localhost:9696
              key: {{HOMEPAGE_VAR_API_KEY}}

    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: http://100.67.54.105:30007
            description: Media Server
            widget:
              type: jellyfin
              url: http://jellyfin:8096
              key: 2727b02a3f414e0b95b9401cbaaa5c02
        - Sonarr:
            icon: sonarr.png
            href: http://100.67.54.105:30002
            description: TV Series
            widget:
              type: sonarr
              url: http://localhost:8989
              key: {{HOMEPAGE_VAR_API_KEY}}
        - Radarr:
            icon: radarr.png
            href: http://100.67.54.105:30003
            description: Movies
            widget:
              type: radarr
              url: http://localhost:7878
              key: {{HOMEPAGE_VAR_API_KEY}}
        - Bazarr:
            icon: bazarr.png
            href: http://100.67.54.105:30006
            description: Subtitles
            widget:
              type: bazarr
              url: http://localhost:6767
              key: {{HOMEPAGE_VAR_API_KEY}}

    - Download:
        - Transmission:
            icon: transmission.png
            href: http://100.67.54.105:30004
            description: Torrent Client
            widget:
              type: transmission
              url: http://localhost:9091
              username: {{HOMEPAGE_VAR_TR_USER}}
              password: {{HOMEPAGE_VAR_TR_PASS}}
        - ARM:
            icon: https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/arm/static/img/arm-logo.png
            href: http://100.67.54.105:30008
            description: Automatic Ripping Machine

  bookmarks.yaml: |
    - GitHub:
        - SecondSync Repo:
            - icon: github.png
              href: https://github.com/TheRealCDH/SecondSync
