apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      containers:
      - name: jellyfin
        image: {{ .Values.images.jellyfin }}
        volumeMounts:
        - name: config-jellyfin
          mountPath: /config
        - name: jellyfin-cache
          mountPath: /cache
        - name: media
          mountPath: /media
          readOnly: true
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: second-sync-media-pvc
      - name: config-jellyfin
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-cache
        emptyDir: {}
