apiVersion: v1
kind: PersistentVolume
metadata:
  name: second-sync-media-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: {{ .Values.mediaHostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: second-sync-media-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  volumeName: second-sync-media-pv
  storageClassName: local-path
