{{- $apps := list "sonarr" "radarr" "transmission" "prowlarr" "bazarr" "overseerr" "jellyfin" -}}
{{- range $app := $apps }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $app }}-config-pvc
  annotations:
    openebs.io/zpool: "zroot"
    openebs.io/cas-type: "localpv-zfs"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.storageClass }}
  resources:
    requests:
      storage: 20Gi
---
{{- end }}
